### ISSUE TITLE
Doesn't start 

### ISSUE THREAD

**Issue by trashken** [Mostafa-Abbasi/HyperTAG#3]
trashken@racknerd-39d704e:~/HyperTAG$ sudo npm start

> hypertag@1.1.0 start
> nodemon index.js

[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
file:///home/trashken/HyperTAG/src/services/telegramServices.js:63
    messagePayload.reply_markup = additionalOptions?.reply_markup || "";
                                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Mostafa-Abbasi** [comment]
Hi, what's your node version? 
You can check it with `node -v` command in the terminal. 
I tested HyperTAG on node v18, and it ran flawlessly, newer node versions had problems, also I didn't test it with versions lower than 18 so make sure you're using the right version.

**Comment by trashken** [comment]
Upgraded my node to v18 using nvm and now it's builds and works. Thanks

**Comment by Mostafa-Abbasi** [comment]
Glad to hear it worked!
